## Numpy: Package for Multidimensional array

In [1]:
import numpy as np

In [3]:
simple_list=[9,5,4]
np.array(simple_list)

array([9, 5, 4])

In [5]:
arr=np.array([1,3,5])
arr

array([1, 3, 5])

In [6]:
list_of_lists=([1,2,3],[5,6,8],[8,6,4])
np.array(list_of_lists)

array([[1, 2, 3],
       [5, 6, 8],
       [8, 6, 4]])

In [7]:
np.arrange[5,65]

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
np.arrange(5,65)

AttributeError: module 'numpy' has no attribute 'arrange'

In [9]:
np.arange[5,65]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [11]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,3)

array([1, 4, 7])

In [15]:
np.arange(1,21,4)

array([ 1,  5,  9, 13, 17])

In [ ]:
### creat whole number upto 50 (0,1,2,3,...50)

In [16]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [21]:
### (5,30,5)
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.zeros(100,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
np.ones(2,5)

TypeError: Cannot interpret '5' as a data type

In [26]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
np.ones([2,5],int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.ones([2,5]),dtype=int

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2048151626.py, line 1)

In [32]:
np.linspace[0,1,5]

TypeError: 'function' object is not subscriptable

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#### in linspace 0 to 5 equally divided number 

In [30]:
np.linspace(2,20,8)

array([ 2.        ,  4.57142857,  7.14285714,  9.71428571, 12.28571429,
       14.85714286, 17.42857143, 20.        ])

In [34]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.eye(10,dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [37]:
np.eye(10),dtype=int

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (804258894.py, line 1)

In [39]:
np.random.rand(2,4)

array([[0.22167072, 0.75705892, 0.1762723 , 0.22768678],
       [0.99569072, 0.63360243, 0.76271741, 0.45389431]])

In [54]:
np.random.rand(3,5)

array([[0.43515929, 0.80536377, 0.47455086, 0.36171211, 0.98772171],
       [0.89106246, 0.81681946, 0.25186414, 0.83287291, 0.09770636],
       [0.38698609, 0.05928165, 0.89334553, 0.43582304, 0.16382945]])

In [41]:
np.random.rand(2,4)

array([[0.06436696, 0.09327651, 0.46548852, 0.68825534],
       [0.9439892 , 0.03525095, 0.79333691, 0.17426012]])

In [ ]:
#### random number of 2x4 matrix below 0 and 1
#### this 0 to 1 distribution is called uniform distribution

In [53]:
arr=np.random.rand(2,4)
arr

array([[0.27738505, 0.00244604, 0.98265525, 0.43250617],
       [0.70995312, 0.88109686, 0.63199479, 0.71162384]])

In [50]:
arr=np.random.rand(2,4)
arr

array([[0.50696511, 0.46125331, 0.6693205 , 0.22783274],
       [0.42497033, 0.80337065, 0.15008067, 0.55871532]])

In [ ]:
#### random number matrix 2x4  both positve and negative value of random numbers
#### it is called standard normal distribution
#### positive and negative distribution is called normal distribution
#### 

In [56]:
np.random.randint(2,10)

8

In [57]:
np.random.randint(2,10)

2

In [60]:
np.random.randint(2,10)

9

In [62]:
np.random.randint(2,10)

7

In [63]:
#### not get last number 10

In [65]:
np.random.randint(20,55,10)

array([44, 31, 42, 23, 43, 34, 53, 39, 49, 43])

In [66]:
np.random.randint(20,55,10)

array([29, 44, 28, 28, 33, 42, 39, 29, 21, 52])

In [ ]:
#### we not get 55 but we get 20 in above 

In [68]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#### first number is 0 and 0 to 30 numbr 30

In [69]:
sample_array=np.arange(100,20)
sample_array

array([], dtype=int32)

In [70]:
sample_array=np.arange(0,100,20)
sample_array

array([ 0, 20, 40, 60, 80])

In [72]:
rand_array=np.random.randint(100,20)
rand_array

ValueError: low >= high

In [73]:
rand_array=np.random.randint(0,100,20)
rand_array

array([75,  5, 87, 62, 85, 72, 77,  7, 45, 90, 28, 22, 68, 92, 12, 31, 29,
       25, 76, 24])

In [75]:
rand_array=np.random.randint(20,100)
rand_array

92

In [8]:
sample_array.reshape(5,6)

ValueError: cannot reshape array of size 5 into shape (5,6)

In [7]:
sample_array=np.arange(0,100,20)
sample_array

array([ 0, 20, 40, 60, 80])

In [6]:
np.random.randint(20,55,10)

array([39, 23, 54, 44, 40, 40, 39, 31, 52, 29])

In [9]:
sample_array.reshape(5,6)

ValueError: cannot reshape array of size 5 into shape (5,6)

In [10]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [13]:
sample_array.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [14]:
sample_array.reshape(5,8)

ValueError: cannot reshape array of size 30 into shape (5,8)

In [15]:
#### error because 10*3=30 and 5*6=30 but 5*8=40 so we cannot reshape it (total elemtes are 30)

In [2]:
rand_array.min()

NameError: name 'rand_array' is not defined

In [4]:
sample_array=np.arange(0,100,20)
sample_array

array([ 0, 20, 40, 60, 80])

In [6]:
rand_array=np.random.randint(0,100,20)
rand_array

array([47, 74, 21, 19, 54, 18, 99, 51, 71,  5, 46, 90, 29, 61,  6, 19,  8,
        8, 47, 78])

In [8]:
rand_array.min()

5

In [9]:
rand_array.max()

99

In [10]:
rand_array.argmin()

9

In [11]:
#### argmin means argument (index value) of minimum value (9)5

In [12]:
rand_array.argmax()

6

In [13]:
#### argmin means argument (index value) of maximum value (6) 99, index starts from 0,1,2,3,......

In [14]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
a=np.random_rand(2,3)
a

AttributeError: module 'numpy' has no attribute 'random_rand'

In [27]:
a=np.random.rand(2,3)
a

array([[0.84545077, 0.02569307, 0.53055776],
       [0.90643213, 0.3806348 , 0.03237892]])

In [28]:
a.T

array([[0.84545077, 0.90643213],
       [0.02569307, 0.3806348 ],
       [0.53055776, 0.03237892]])

In [30]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
sample_array[8]

18

In [ ]:
#### sample_array[8] is index value of array

In [32]:
sample_array(8)

TypeError: 'numpy.ndarray' object is not callable

In [33]:
sample_array[2:5]

array([12, 13, 14])

In [ ]:
#### 2:5 means index 2,3,4 of array

In [34]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [35]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [36]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])